apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful5-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "local-path"
  volumeMode: Filesystem 
  persistentVolumeReclaimPolicy: Retain 
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-local-agent-1
