apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-namespace-sts1
  namespace: namespace-sts1
provisioner: your-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.0
parameters:
  server: 10.0.2.4
  path: "/srv/kubernetes"
