kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-claim-sts2
#  namespace: namespace-sts2
spec:
  storageClassName: ""
  volumeName: pv-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
