apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    type: pv-nfs
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
  - nfsvers=4.0
  nfs:
    server: 10.0.2.4
    path: "/srv/kubernetes"
    readOnly: false

#  storageClassName: "nfs-client " #scoate storage name
#  persistentVolumeReclaimPolicy: Recycle #Retain