apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful1
  namespace: namespace1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful1
  serviceName: stateful1
  template:
    metadata:
      labels:
        app: stateful1
    spec:
      nodeName: k3d-local-agent-1 
      containers:
        - name: stateful1
          image: petrumariuta/stateful:latest
#          ports:
#            - containerPort: 86
          command:
            - /bin/sh
            - -c
          args:
            - |
              useradd -m user1
              key=1
              while true; do
                  variable=$(ps -awx)
                  echo "{\"$key\": \"$variable\"}" >> /srv/kubernetes/file1.json
                  key=$((key + 1))
                  sleep 10000  
              done

          volumeMounts:
            - name: pv-nfs
              mountPath: /srv/kubernetes
      volumes:
        - name: pv-nfs
          persistentVolumeClaim:
            claimName: nfs-pvc-claim-sts1


#ps -awx >> /fisiere/file1.md
#ps -awx >> /srv/kubernetes/file1.md

#          securityContext:
#            runAsUser: 1000  # User id of "user1" from /etc/passwd
#            runAsGroup: 1000 # Group id user1 from /etc/group