apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful5
  serviceName: stateful5
  template:
    metadata:
      labels:
        app: stateful5
    spec:
      containers:
        - name: apache-task5
          image: petrumariuta/apache-task5:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pv-nfs
              mountPath: /srv/kubernetes
      volumes:
        - name: pv-nfs
          persistentVolumeClaim:
            claimName: nfs-pvc-claim


#ps -awx >> /fisiere/file1.md
#ps -awx >> /srv/kubernetes/file1.md